### ISSUE TITLE
Hunt for host discovery commands

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/tahiti-wfms#1]
**Acceptance Criteria**  
This story will be considered complete when the playbook has been updated and the report has been written.

**Tasks***
- [ ] Validate Security Gap Still Exists
- [ ] Refine Hypothesis
- [ ] Re-Validate Data Visibility / Usability 
- [ ] Gather and Analyze Data According to the Playbook 
- [ ] Automate Steps As You Can/Go
- [ ] Update the Playbooks
- [ ] Write Report
- [ ] Share Findings

Note: Although not in this list of tasks, incidents should be escalated as they are found.
