### ISSUE TITLE
Create/Modify Abstract  Enumerate Remote Access Tools

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/tahiti-wfms#2]
**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the Merge Request has been approved.

**Tasks**
- [ ] Create New Branch
- [ ] Create/Update/Delete the Abstract
- [ ] Create Merge Request
- [ ] Close Issue
