### ISSUE TITLE
Hunt for Rogue Remote Access Tools

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/tahiti-wfms#3]
**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the issue is no longer needed, it should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Still Exists
- [ ] Refine Hypothesis
- [ ] Re-Validate Data Visibility / Usability 
- [ ] Gather and Analyze Data According to the Playbook 
- [ ] Automate Steps As You Can/Go
- [ ] Update the Playbooks
- [ ] Write Report
- [ ] Share Findings
- [ ] Close Issue

**Note:** Incidents should be escalated as they are found.
